USE [Meliasoft2016_NB]
GO

/*--------------- [Web_ReportChartTypes] table  ---------------*/

/****** Object:  Table [dbo].[Web_ReportChartTypes]    Script Date: 2019/08/26 18:47:26 ******/
DROP TABLE [dbo].[Web_ReportChartTypes]
GO


/****** Object:  Table [dbo].[Web_ReportChartTypes]     Script Date: 2019/08/26 18:47:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Web_ReportChartTypes](
	[TypeId] [int] IDENTITY(1,1) NOT NULL,
	[TypeName] [nvarchar](50) NULL,
	[StyleName] [nvarchar](50) NULL,
	[ShowingOrder] [int] NULL,
	[ChartConfig] [nvarchar](4000) NULL,
	[ChartDemoImg] [nvarchar](500) NULL,
	[ChartDataSample] [nvarchar](4000) NULL,
	[AvailableFlg] [bit] NULL,
	[Note] [nvarchar](500) NULL,
 CONSTRAINT [PK_Web_ReportChartTypes] PRIMARY KEY CLUSTERED 
(
	[TypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar','layout_3x','3','{"type": "bar", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{"value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal"}, "tooltip": { "text": "%v", "padding": "5 10"}, "styles":["#FFD700","orange","yellow","#DEB887", "green","blue", "#D2691E","purple", "#B8860B", "brown","#9370DB", "#C71585"] }, "plotarea": {"adjust-layout": true}, "scale-y":{ "short":true }, "scale-x": {"label": { "text": "[chart_subtitle]"}, "labels": [chart_x_captions]}, "series": [chart_data]}','/Images/Charts/03_bar_layout_3x.png','[{"values": [37.47, 57.59, 45.65, 37.43],"alpha": 0.95,"borderRadiusTopLeft": 7,"background-color": "#8993c7","text": "Ban giám đốc"}, {"values": [22.02, 39.59, 22.5, 27.91],"borderRadiusTopLeft": 7,"alpha": 0.95,"background-color": "#fdb462","text": "Phòng kinh doanh"}, {"values": [13.4, 14.11, 14.89, 16.86],"alpha": 0.95,"borderRadiusTopLeft": 7,"background-color": "#8dd3c7","text": "Phòng triển khai"}, {"values": [18.53, 24.52, 20.4, 23.38],"borderRadiusTopLeft": 7,"alpha": 0.95,"background-color": "#fb8072","text": "Phòng sản phẩm"}, {"values": [17.09, 25.59, 19.74, 19.34],"borderRadiusTopLeft": 7,"alpha": 0.95,"background-color": "#80b1d3","text": "Phòng bảo hành"}, {"values": [2.31, 2.36, 2.42, 2.52],"borderRadiusTopLeft": 7,"alpha": 0.95,"background-color": "#b3de69","text": "Other"}]','True','bar chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('pie','standard','13','{"type": "pie", "title": {"fontColor": "#605F3D","text": "[chart_title]","align": "left","offsetX": 10,"fontFamily": "Open Sans","fontSize": "18px"},"subtitle": {"offsetX": 10,"offsetY": 10,"fontColor": "#8e99a9","fontFamily": "Open Sans","fontSize": "14","text": "[chart_subtitle]","align": "left"},"scale":{ "size-factor":0.75}, "plot": {"borderColor": "#993300","borderWidth": 1, "tooltip": { "text": "%t: %v ", "padding": "5 10"}, "valueBox": {"placement": "out","text": "%t: %npv%"}, "animation": {"effect": 2,"method": 2,"speed": 900,"sequence": 1,"delay": 3000}},"plotarea": {"margin": "20 0 0 0"},"series": [chart_data]} ','/Images/Charts/13_pie_standard.png','[{"values": [11.38],"text": "Internet Explorer","backgroundColor": "#50ADF5"}, {"values": [56.94],"text": "Chrome","backgroundColor": "#FF7965","detached": true}, {"values": [14.52],"text": "Firefox","backgroundColor": "#FFCB45","detached": true}, {"text": "Safari","values": [9.69],"backgroundColor": "#6877e5"}, {"text": "Other","values": [7.48],"backgroundColor": "#6FB07F"}]','True','pie chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar','standard','1','{"type": "bar", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{"value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal"}, "tooltip": { "text": "%v", "padding": "5 10"}, "styles":["#FFD700","orange","yellow","#DEB887", "green","blue", "#D2691E","purple", "#B8860B", "brown","#9370DB", "#C71585"] }, "plotarea": {"adjust-layout": true}, "scale-y":{ "short":true }, "scale-x": {"label": { "text": "[chart_subtitle]"}, "labels": [chart_x_captions]}, "series": [chart_data]}','/Images/Charts/01_bar_standard.png','[{"values": [20, 40, 25, 50, 15, 45, 33, 34]}]','True','simplest bar');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar3d','standard','8','{"type": "bar3d","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true},"scale-x": {"labels": [chart_x_captions]}, "scale-y":{ "short":true }, "plot":{ "value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal"  } }, "series": [chart_data]}','/Images/Charts/08_bar3d_standard.png','[{"values":[20,40,25,50,15,45,33,34]},{"values":[5,30,21,18,59,50,28,33]},{"values":[30,5,18,21,33,41,29,15]}]','True','simplest bar 3d');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('hbar','standard','11','{"type": "hbar","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "scale-x": {"short":true, "labels": [chart_x_captions]},  "plot":{ "value-box":{ "short":true  } }, "series": [chart_data]}','/Images/Charts/11_hbar_standard.png','[{"values":[20,40,25,50,15,45,33,34]},{"values":[5,30,21,18,59,50,28,33]},{"values":[30,5,18,21,33,41,29,15]}]','True','v-simplest Horizontal bar charts');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('hbar3d','standard','12','{"type": "hbar3d","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "scale-x": {"short":true, "labels": [chart_x_captions]}, "plot":{ "value-box":{ "short":true  } }, "series": [chart_data]}','/Images/Charts/12_hbar3d_standard.png','[{"values":[20,40,25,50,15,45,33,34]},{"values":[5,30,21,18,59,50,28,33]},{"values":[30,5,18,21,33,41,29,15]}]','True','v-simplest Horizontal bar 3d charts');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar','100p_stacked','5','{"type": "bar", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{"stacked":true,"stack-type":"100%", "value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal"}},"scale-y":{"min-value":0,"max-value":100}, "scale-x": {"labels": [chart_x_captions]}, "series": [chart_data]}','/Images/Charts/05_bar_100p_stacked.png','[{"values":[20,40,25,50,15,45,33,34]},{"values":[5,30,21,18,59,50,28,33]},{"values":[30,5,18,21,33,41,29,15]}]','True','100% stacked column or bar chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar','stacked','4','{"type": "bar", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{"stacked":true, "value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal"}},"scale-y":{"min-value":0,"max-value":100}, "scale-x": {"labels": [chart_x_captions]}, "series": [chart_data]}','/Images/Charts/04_bar_stacked.png','[{"values":[20,40,25,50,15,45,33,34]},{"values":[5,30,21,18,59,50,28,33]},{"values":[30,5,18,21,33,41,29,15]}]','True','Standard Stacked Bar Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('pie3d','standard','14','{"type": "pie3d", "title": {"fontColor": "#605F3D","text": "[chart_title]","align": "left","offsetX": 10,"fontFamily": "Open Sans","fontSize": "18px"},"subtitle": {"offsetX": 10,"offsetY": 10,"fontColor": "#8e99a9","fontFamily": "Open Sans","fontSize": "14","text": "[chart_subtitle]","align": "left"},"scale":{ "size-factor":0.75}, "plot": {"borderColor": "#993300","borderWidth": 1, "tooltip": { "text": "%t: %v ", "padding": "5 10"}, "valueBox": {"placement": "out","text": "%t: %npv%"}, "animation": {"effect": 2,"method": 2,"speed": 900,"sequence": 1,"delay": 3000}},"plotarea": {"margin": "20 0 0 0"},"series": [chart_data]} ','/Images/Charts/14_pie3d_standard.png','[{"values": [11.38],"text": "Internet Explorer","backgroundColor": "#50ADF5"}, {"values": [56.94],"text": "Chrome","backgroundColor": "#FF7965","detached": true}, {"values": [14.52],"text": "Firefox","backgroundColor": "#FFCB45","detached": true}, {"text": "Safari","values": [9.69],"backgroundColor": "#6877e5"}, {"text": "Other","values": [7.48],"backgroundColor": "#6FB07F"}]','True','pie 3d chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('ring','standard','15','{"type": "ring","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data]}','/Images/Charts/15_ring_standard.png','[{"values":[59]},  {"values":[55]},  {"values":[30]},  {"values":[28]},  {"values":[15]}]','True','ring chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('ring3d','standard','16','{"type":" ring3d","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data]}','/Images/Charts/16_ring3d_standard.png','[{"values":[59]},  {"values":[55]},  {"values":[30]},  {"values":[28]},  {"values":[15]}]','True','ring 3d chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('area','standard','17','{"type": "area","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data]}','/Images/Charts/17_area_standard.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]},  {"values":[30,5,18,21,33,41,29,15]}]','True','area chart - simple');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('area3d','standard','18','{"type": "area3d","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{  "alpha-area":0.7},"series": [chart_data]}','/Images/Charts/18_area3d_standard.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]},  {"values":[30,5,18,21,33,41,29,15]}]','True','area chart 3d  - simple');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('varea','standard','19','{"type": "varea","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data]}','/Images/Charts/19_varea_standard.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]},  {"values":[30,5,18,21,33,41,29,15]}]','True','varea chart - simple');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bullet','standard','20','{"type": "bullet","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data]}','/Images/Charts/20_bullet_standard.png','[{"values":[20,40,25,50,15,45,33,34],"goals": [25,43,30,40,21,59,35,31]}]','True','bullet chart (with goals)');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('hbullet','standard','21','{"type": "hbullet","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data]}','/Images/Charts/21_hbullet_standard.png','[{"values":[20,40,25,50,15,45,33,34],"goals": [25,43,30,40,21,59,35,31]}]','True','h-bullet chart (with goals)');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar','overlapping','6','{"type": "bar","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "scale-y":{ "short":true }, "plot": {"value-box":{ "short": true },  "bars-overlap": "100%"}, "tooltip": { "text": "%t: %v ", "padding": "5 10"}, "series": [chart_data]}','/Images/Charts/06_bar_overlapping.png','[{"values": [70,50,75,51,70,73,67,46], "background-color": "#2B2836", "alpha": 0.5, "hover-state": {   "visible": false }, "max-trackers": 0  },  { "values": [73,77,91,86,67,76,88,96], "background-color": "#C42E53", "alpha": 0.9, "bar-width": "40%"  }]','True','Overlapping Bar Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar','offset_values','7','{"type": "bar","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{"value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal" } }, "scale-y":{ "short":true }, "tooltip": { "text": "%t: %v ", "padding": "5 10"},  "series": [chart_data]}','/Images/Charts/07_bar_offset_values.png','[{"values":[20,40,25,50,15,45,33,34], "offset-values":[0,3,5,15,28,30,4,9]}]','True','Floating Bar Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar3d','cylinder','9','{"type": "bar3d","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{"aspect":"cylinder", "value-box":{ "short":true  } }, "scale-y":{ "short":true }, "series": [chart_data]}','/Images/Charts/09_bar3d_cylinder.png','[{"values":[20,40,25,50,15,45,33,34]},{"values":[5,30,21,18,59,50,28,33]},{"values":[30,5,18,21,33,41,29,15]}]','True','Cylinder Bar Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar3d','pyramid','10','{"type": "bar3d","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true},  "plot":{"aspect":"pyramid" }, "series": [chart_data]}','/Images/Charts/10_bar3d_pyramid.png','[{"values":[20,40,25,50,15,45,33,34]},{"values":[5,30,21,18,59,50,28,33]},{"values":[30,5,18,21,33,41,29,15]}]','True','Pyramid Bar Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('line','standard','22','{"type": "line","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data]}','/Images/Charts/22_line_standard.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]},  {"values":[30,5,18,21,33,41,29,15]}]','True','line chart - simple');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('vline','standard','23','{"type": "vline","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data]}','/Images/Charts/23_vline_standard.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]},  {"values":[30,5,18,21,33,41,29,15]}]','True','v-line chart - simple');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('line','spline','24','{"type": "line","title": {"text": "[chart_title]","font-color": "#605F3D,"backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{ "aspect":"spline" }, "series": [chart_data]}','/Images/Charts/24_line_spline.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]},  {"values":[30,5,18,21,33,41,29,15]}]','True','Spline Line Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('line','stacked','25','{"type": "line","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{ "stacked":true }, "series": [chart_data]}','/Images/Charts/25_line_stacked.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]},  {"values":[30,5,18,21,33,41,29,15]}]','True','Standard Stacked Line Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('line','100p_stacked','26','{"type": "line","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{ "stacked":true, "stack-type":"100%" }, "scale-y":{"min-value":0,"max-value":100 }, "series": [chart_data]}','/Images/Charts/26_line_100p_stacked.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]},  {"values":[30,5,18,21,33,41,29,15]}]','True','100% Stacked Line Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('line','category_scale','27','{"type": "line", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plotarea": {"adjust-layout":true }, "scale-x": {"label":{ "text":"[chart_subtitle]"}, "labels":[chart_x_captions]}, "series": [chart_data]}','/Images/Charts/27_line_category_scale.png','[{"values":[20,40,25,50,15,45,33,34]},  {"values":[5,30,21,18,59,50,28,33]}]','True','Category Scale');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('mixed','standard','28','{"type": "mixed","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true},  "plot": { "tooltip": { "text": "%t" }},"series": [chart_data] }','/Images/Charts/28_mixed_standard.png','[{"type": "area","values": [34, 70, 40, 75, 33, 50, 65],"aspect": "stepped","contour-on-top": false,"text": "Area Chart"},{"type": "bar","values": [49, 30, 21, 15, 59, 51, 69],"bar-width": "50%","text": "Bar Chart"},{"type": "line","values": [5, 9, 3, 19, 7, 15, 14],"aspect": "spline","text": "Line Chart"}]','True','The chart types that can be used with our default mixed chart are: "area", "bar", "line", "bullet", "scatter", "bubble", "stock", and "range".');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('hmixed','standard','29','{"type": "hmixed","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true},  "plot": { "tooltip": { "text": "%t" }},"series": [chart_data] }','/Images/Charts/29_hmixed_standard.png','[{"type": "area","values": [34, 70, 40, 75, 33, 50, 65],"aspect": "stepped","contour-on-top": false,"text": "Area Chart"},{"type": "bar","values": [49, 30, 21, 15, 59, 51, 69],"bar-width": "50%","text": "Bar Chart"},{"type": "line","values": [5, 9, 3, 19, 7, 15, 14],"aspect": "spline","text": "Line Chart"}]','True','"varea", "hbar", "vline", "hbullet", "hscatter", and "hbubble".');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('nestedpie','standard','30','{"type": "nestedpie", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data] }','/Images/Charts/30_nestedpie_standard.png','[{"values":[59,55,30]},{"values":[60,50,35]},{"values":[50,40,30]} ]','True','Specify the chart type by adding a "type" attribute to the chart object and setting the value to "nestedpie". ');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('nestedpie','donut','31','{"type": "nestedpie", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plot":{ "slice-start":"35%" }, "series": [chart_data] }','/Images/Charts/31_nestedpie_donut.png','[{"values":[59,55,30]},{"values":[60,50,35]},{"values":[50,40,30]} ]','True','You can create a nested donut chart by adding a "slice-start" attribute to the "plot" object. ');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('pop-pyramid','standard','32','{"type": "pop-pyramid", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data] }','/Images/Charts/32_pop-pyramid_standard.png','[{ "data-side": 1, "values": [1656154, 1787564 ]},{ "data-side": 2, "values": [1656154, 1787564 ]} ]','False','Support: hbar | bar | area | varea | line | vline');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('pop-pyramid','bar','33','{"type": "pop-pyramid", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "options": { "aspect": "bar" }, "series": [chart_data] }','/Images/Charts/33_pop-pyramid_bar.png','[{ "data-side": 1, "values": [1656154, 1787564 ]},{ "data-side": 2, "values": [1656154, 1787564 ]} ]','False','Support: hbar | bar | area | varea | line | vline');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('pop-pyramid','area','34','{"type": "pop-pyramid","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true},  "options": { "aspect": "area" }, "series": [chart_data] }','/Images/Charts/34_pop-pyramid_area.png','[{ "data-side": 1, "values": [1656154, 1787564 ]},{ "data-side": 2, "values": [1656154, 1787564 ]} ]','False','Support: hbar | bar | area | varea | line | vline');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('pop-pyramid','varea','35','{"type": "pop-pyramid","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true},  "options": { "aspect": "varea" }, "series": [chart_data] }','/Images/Charts/35_pop-pyramid_varea.png','[{ "data-side": 1, "values": [1656154, 1787564 ]},{ "data-side": 2, "values": [1656154, 1787564 ]} ]','False','Support: hbar | bar | area | varea | line | vline');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('radar','standard','36','{"type": "radar", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data] }','/Images/Charts/36_radar_standard.png','[{ "values": [59, 30, 65, 34, 40] }, { "values": [76, 60, 11, 21, 99] }, { "values": [34, 0, 0, 30, 10] }]','True','Radar Chart');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('radar','area','37','{"type": "radar","title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true},  "plot": { "aspect": "area" }, "scale-v": { "values": "0:100:25", "labels": ["", "", "", "", ""], "ref-line": { "line-color": "none" }, "guide": { "line-style": "solid" } }, "scale-k": { "values": "0:330:30", "format": "%v°", "aspect": "circle", "guide": { "line-style": "solid" } }, "series": [chart_data] }','/Images/Charts/37_radar_area.png','[{ "values": [59, 30, 65, 34, 40, 33, 31, 90, 81, 70, 100, 28] }, { "values": [30, 100, 90, 99, 59, 34, 5, 3, 12, 15, 16, 75, 34] }, { "values": [34, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 100] }]','True','Polar charts appear similar to radars, but their data is displayed in relation to angles rather than variables. ');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('range','standard','38','{"type": "range", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data] }','/Images/Charts/38_range_standard.png','[{"values":[ [15,30], [20,40], [16,35], [21,30], [25,45], [18,27], [23,35], [29,39], [27,30], [19,34] ]} ]','True','range charts or graphs display groups of data that are bound by lower and upper values. ');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('waterfall','standard','39','{"type": "waterfall", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data] }','/Images/Charts/39_waterfall_standard.png','[{ "values": [420,210,-170,-140,"SUM"] } ]','True','Waterfall charts can be useful to represent the cumulative effect of sequentially introduced positive or negative values.');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('hwaterfall','standard','40','{"type": "hwaterfall", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data] }','/Images/Charts/40_hwaterfall_standard.png','[{ "values": [420,210,-170,-140,"SUM"] } ]','True','Waterfall charts can be useful to represent the cumulative effect of sequentially introduced positive or negative values.');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('waterfall3d','standard','41','{"type": "waterfall3d", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data] }','/Images/Charts/41_waterfall3d_standard.png','[{ "values": [420,210,-170,-140,"SUM"] } ]','True','Waterfall charts can be useful to represent the cumulative effect of sequentially introduced positive or negative values.');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('hwaterfall3d','standard','42','{"type": "hwaterfall3d", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "series": [chart_data] }','/Images/Charts/42_hwaterfall3d_standard.png','[{ "values": [420,210,-170,-140,"SUM"] } ]','True','Waterfall charts can be useful to represent the cumulative effect of sequentially introduced positive or negative values.');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar','standard_default_color','2','{"type": "bar", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plotarea": {"adjust-layout": true},"scale-y":{ "short":true }, "plot":{ "value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal" } },"scale-x": {"label": { "text": "[chart_subtitle]"},"labels": [chart_x_captions]}, "series": [chart_data]} ','/Images/Charts/02_bar_standard_default_col.png','[{"values": [20, 40, 25, 50, 15, 45, 33, 34]}]','True','simplest bar');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('bar','bar_overlap_progress','7','{"type": "bar", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plotarea": {"adjust-layout": true},"scale-y":{ "short":true }, "plot":{ "bars-overlap": "100%", "value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal" } },"scale-x": {"label": { "text": "[chart_subtitle]"},"labels": [chart_x_captions]}, "series": [chart_data]} ','/Images/Charts/06_bar_overlapping_progress.png','[ {  "values": [70, 50, 75, 51, 70, 73, 67, 46],  "offset-values": [0, 3, 5, 15, 18, 20, 4, 9],  "backgroundColor": "#2B2836",  "alpha": 0.5,  "hover-state": { "visible": false  },  "max-trackers": 0 }, {  "values": [53, 37, 51, 66, 37, 46, 58, 36],  "offset-values": [0, 3, 5, 15, 18, 20, 4, 9],  "backgroundColor": "#C42E53",  "alpha": 0.9,  "bar-width": "40%" } ]','True','bars_overlap_progress');
INSERT INTO [dbo].[Web_ReportChartTypes] ([TypeName] ,[StyleName] ,[ShowingOrder] ,[ChartConfig] ,[ChartDemoImg] ,[ChartDataSample] ,[AvailableFlg] ,[Note]) VALUES ('hbar','bar_overlap_progress','7','{"type": "hbar", "title": {"text": "[chart_title]","font-color": "#605F3D","backgroundColor": "none","font-size": "16px","align": "left","alpha": 1,"adjust-layout":true}, "plotarea": {"adjust-layout": true},"scale-y":{ "short":true }, "plot":{ "bars-overlap": "100%", "value-box":{ "text": "%t", "angle": -90, "placement": "bottom-in","font-color": "black", "offset-y": -85, "align":"left", "font-weight": "normal" } },"scale-x": {"label": { "text": "[chart_subtitle]"},"labels": [chart_x_captions]}, "series": [chart_data]} ','/Images/Charts/06_hbar_overlapping_progres.png','[ {  "values": [70, 50, 75, 51, 70, 73, 67, 46],  "offset-values": [0, 3, 5, 15, 18, 20, 4, 9],  "backgroundColor": "#2B2836",  "alpha": 0.5,  "hover-state": { "visible": false  },  "max-trackers": 0 }, {  "values": [53, 37, 51, 66, 37, 46, 58, 36],  "offset-values": [0, 3, 5, 15, 18, 20, 4, 9],  "backgroundColor": "#C42E53",  "alpha": 0.9,  "bar-width": "40%" } ]','True','bars_overlap_progress (horizontal)');



/*--------------- [Web_ReportCharts] table  ---------------*/

/****** Object:  Table [dbo].[Web_ReportCharts]    Script Date: 2019/08/26 18:48:13 ******/
DROP TABLE [dbo].[Web_ReportCharts]
GO


/****** Object:  Table [dbo].[Web_ReportCharts]    Script Date: 2019/08/26 18:48:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Web_ReportCharts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ReportId] [int] NULL,
	[Title] [nvarchar](500) NULL,
	[Subtitle] [nvarchar](500) NULL,
	[Visible] [bit] NULL,
	[AutoSpeech] [bit] NULL,
	[ChartTypeId] [int] NULL,
	[SelectedColumns] [nvarchar](500) NULL,
	[SelectedRows] [nvarchar](500) NULL,
	[Note] [nvarchar](500) NULL,
 CONSTRAINT [PK_Web_ReportCharts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Web_ReportCharts] ADD  CONSTRAINT [DF_Web_ReportCharts_Visible]  DEFAULT ((1)) FOR [Visible]
GO

ALTER TABLE [dbo].[Web_ReportCharts] ADD  CONSTRAINT [DF_Web_ReportCharts_AutoSpeech]  DEFAULT ((0)) FOR [AutoSpeech]
GO

/*--------------- [Web_ReportChart_SavedInfo] table  ---------------*/


/****** Object:  Table [dbo].[Web_ReportChart_SavedInfo]    Script Date: 2019/08/26 18:49:37 ******/
DROP TABLE [dbo].[Web_ReportChart_SavedInfo]
GO

/****** Object:  Table [dbo].[Web_ReportChart_SavedInfo]    Script Date: 2019/08/26 18:49:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Web_ReportChart_SavedInfo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AccountName] [nvarchar](50) NULL,
	[SavedInfo] [nvarchar](500) NULL,
 CONSTRAINT [PK_Web_ReportChart_SavedInfo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




